# Generated by Django 3.1.4 on 2021-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='social_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
